version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: db
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "mariokart-slack"
      #expose:
      #  - "5432"
    restart: on-failure
  app:
    image: mariokart-bot-app
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    volumes:
      - ./app:/code/app
      - ./config:/code/config
      - ./db:/code/db
      - ./public:/code/public
      - ./app.rb:/code/app.rb
      - ./config.ru:/code/config.ru
      - ./console.rb:/code/console.rb
    ports:
      - "3001:3001"
    restart: always
    environment:
      - DATABASE_URL
      - RAILS_ENV
      - SLACK_TOKEN
      - CHANNEL_ID
      - SESSION_SECRET
      - SLACK_CLIENT_ID
      - SLACK_CLIENT_SECRET
      - LOGIN_REDIRECT_URL
      - BOT_ACCESS_TOKEN
    command: bash -c "source /usr/local/rvm/scripts/rvm && bundle exec rackup config.ru -p 3001 -o 0.0.0.0"
    depends_on:
      - postgres

volumes:
  postgres:
