name: publish

on: [push]

jobs:
  publish-mariokart-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Corrected token reference

      - name: Build and push mariokart ELO image
        run: |
          docker build . --file Dockerfile --tag ghcr.io/antoinederengerve/mariokart-slack:latest
          docker push ghcr.io/antoinederengerve/mariokart-slack:latest
